### ISSUE TITLE
Invalid Syntax Error; python3 users; Pull Request Created

### ISSUE THREAD

**Issue by WiFisunset** [pimylifeup/Light_Sensor#1]
Whenever I try to run the code, I get the following error:
>>> %Run Light_Sensor.py
Traceback (most recent call last):
  File "/home/pi/LightSense.py", line 35
    print rc_time(pin_to_circuit)
--------------------------------------------------------------------------

**Comment by death-droid** [comment]
Hi @WiFisunset,

What version of Python are you using to run the script?

Cheers,
Emmet

**Comment by WiFisunset** [comment]
(via python -v) It's Python Version 2.7, but I always have to type sudo python3 'insertPythonFileHere.py' in order to remedy some board errors such as "ImportError: No module named 'board'".

I actually didn't try this code without the python3 command (ie. using the normal 'sudo python' call).

Do you think the python3 is what triggered my error?

Edit: I tested the code, and yup that's the issue. So my issue in this case would be more for python Version 3 users (or in my case people who use python3 command by default).

**Comment by death-droid** [comment]
Corrected this in https://github.com/pimylifeup/Light_Sensor/commit/197534d40e5334cb53705841ac015d654a6b222c 

Python 3 required print to be utilized as a function and not a statement.
